name: Flask App CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: DevOps2024*
          POSTGRES_DB: webappdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: localhost
      DB_NAME: ${{ secrets.DB_NAME }}
      FLASK_ENV: testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests and log output
        run: |
          mkdir -p test-results
          echo "Starting tests..."
          python -m unittest discover -v tests | tee test-results/unit-test.log
          echo "Tests complete."

      - name: Upload unit test logs
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-logs
          path: test-results/unit-test.log

