name: Deploy to Production (RHEL)

on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Ansible Playbook on RHEL EC2
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy-prod.yml
          inventory: ansible/inventory.ini
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --extra-vars "ansible_python_interpreter=/usr/bin/python3"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}

