name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/Linux2025.pem
          chmod 600 ~/.ssh/Linux2025.pem

      - name: Disable Ansible host key checking
        run: echo "ANSIBLE_HOST_KEY_CHECKING=False" >> $GITHUB_ENV

      - name: Test SSH Connection (optional)
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/Linux2025.pem ubuntu@3.98.142.131 'echo SSH connection success!'

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy-prod.yml
          options: 
            --inventory ansible/inventory.ini
            --extra-vars "ansible_python_interpreter=/usr/bin/python3"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
